### ISSUE TITLE
Ecrire un solveur en Python

### ISSUE THREAD

**Issue by vxid** [vxid/rmn#1]
@edernlehyaric J'ai commencé un programme un peu moche en objet pour avoir des fonctionalités similaires à ton solveur en OPL. J'ai pas encore eu le temps de lire la doc associée mais ça risue de pas être aussi évident que ton programme.

**Comment by vxid** [comment]
btw: https://www.nmrglue.com/

**Comment by edernlehyaric** [comment]
j'ai continué mon truc opl de mon côté, je me suis lancé dans la generation
de molécule à partir d'un spectre 1d, et oh mon dieu j'aurai jamais dû
tenter ça en opl ... le langage refuse les matrices dans les custom types,
et pas d'objet donc adios.
je l'ai fait en python du coup, mais je sais pas exactement si ça va être
utile car je viens de voir que t'as aussi commencer le solveur. honnetement
trop fatigué pour regarder ça ce soir je verrai demain.
Tchuss

2017-11-28 18:29 GMT+01:00 vxid <notifications@github.com>:

**Comment by vxid** [comment]
Ok. Bossons dessus ensemble alors, on s'appelle quand je finis de donner cours

**Comment by vxid** [comment]
Si tu peux commencer à chercher comment combiner les groupes qu'on a à la fin ça serait top. Perso je me charge de détecter les groupes avec les infos de la rmn, j'ai trouvé des infos top dessus hier.

**Comment by ColineUVSQ** [comment]
@vxid  pourquoi tu dis que l'aire sous les pics correspond au nombre de H sans les H des OH ? L'aire sous les pics donne une valeur proportionnelle au nombre de H dans toute la molécule, non ?

**Comment by vxid** [comment]
Oui et non. Sur CH3-CH2-CH2-OH le H de OH n'est pas compté. Sinon oui, il y a proportionalité: une somme des aires de 5 indique que l'on peut avoir 5, 10, 15 ... Hydrogènes.

**Comment by ColineUVSQ** [comment]
Il n'y a pas de pic pour le H du OH ?

**Comment by ColineUVSQ** [comment]
Mouais, c'est bizarre. En principe, le fait que le H du OH s'accroche au solvant fait que les autres H ne voient pas ce H-là comme voisin, même s'ils se trouvent à moins de 3 liaisons de distance. Mais il devrait quand même former un pic... J'ai demandé à Quessette de nous envoyer les spectres du propanol, faits par le prof de chimie. On verra si c'est comme ça aussi sur ces spectres-là.

**Comment by ColineUVSQ** [comment]
Avant de dire qu'un "motif" moléculaire peut correspondre à une famille de la RMN 1D H, on pourrait rajouter la contrainte qui vérifie que le nombre de H dans le motif est bien le même que celui dans la famille (qu'on trouve avec les valeurs de courbes d'intégration (area dans le code de vxid)), non ?
Ca enlèverait des possibilités.

**Comment by edernlehyaric** [comment]
vous allez à la fac pour quelle heure ?

**Comment by ColineUVSQ** [comment]
Moi, j'y suis.

**Comment by vxid** [comment]
Vers 13h pour moiOn Dec 4, 2017 10:32 AM, ColineUVSQ <notifications@github.com> wrote:Moi, j'y suis.

**Comment by edernlehyaric** [comment]
Sac abandonné à Massy. Un mec en tenue démineur sur les voies,ah dakor...

**Comment by edernlehyaric** [comment]
Prochain train dans 50 min, je serai à la fac dans 1h30 mini

**Comment by edernlehyaric** [comment]
T'es dans quelle salle ?

On Dec 4, 2017 11:07, "Edern Le Hyaric" <edern.lehyaric@gmail.com> wrote:

Prochain train dans 50 min, je serai à la fac dans 1h30 mini

**Comment by vxid** [comment]
Damn. C'est pas plus simple de passer par Paris limite?On Dec 4, 2017 12:07 PM, edernlehyaric <notifications@github.com> wrote:Prochain train dans 50 min, je serai à la fac dans 1h30 mini

**Comment by ColineUVSQ** [comment]
Avec Bintou, on est à la MDE à Buffon.
