### ISSUE TITLE
Ecriture du rapport : Partie description RMN

### ISSUE THREAD

**Issue by ColineUVSQ** [vxid/rmn#3]

**Comment by ColineUVSQ** [comment]
@vxid C'est toi qui as gardé le rapport de Mael et Stephie ? :)

**Comment by vxid** [comment]
Oui j'ai oublié ! Je peix t'envoyer des photos!

**Comment by ColineUVSQ** [comment]
Ok, merci. Par mail du coup ?

**Comment by vxid** [comment]
https://drive.google.com/folderview?id=1-lbEANI9pJL0gWf2_um7_xKJ_VnlG40R

**Comment by ColineUVSQ** [comment]
Merci !
