### ISSUE TITLE
connexité

### ISSUE THREAD

**Issue by BintouFOFANA** [vxid/rmn#4]
je pense que j'ai une idée pour la connexité du graphe.
On est d'accord les matrices données par OPL ne sont pas vraiment des matrices d'adjacences. 
On sait que un graphe qui a k composantes connexes a ( n- k) arêtes au min, et donc un graphe non orienté connexe (n - 1) arêtes au min. 
Du coup on pourrait mettre des contraintes sur le nombre d’arêtes

**Comment by ColineUVSQ** [comment]
Ce serait donc en se disant que les liaisons multiples correspondent à une arête dans le graphe ?

**Comment by BintouFOFANA** [comment]
oui c'est cela, parce que sinon ça ne marcherait pas
