### ISSUE TITLE
Algorithme en pseudo-code

### ISSUE THREAD

**Issue by ColineUVSQ** [vxid/rmn#5]
Avec Bintou, ce matin, on a essayé de "formaliser" un peu l'algorithme, et de l'écrire en pseudo-code, pour y voir plus clair : Est-ce que ça correspond bien à ce que vous faites dans vos programmes ?

**Algo 1** :  obtenir tous les sous-ensembles possibles de familles
Entrée : 
     -np= Nombre de pics = nombre de familles (RMN 1D de H)
     -valppm = liste des valeurs de ppm de chaque groupe d’hydrogènes (RMN 1D de H)
     -nbH = liste des valeurs des courbes d’intégration donnant le nombre de H dans chaque famille (RMN 1D de H)
     -table de correspondance qui associe à un motif moléculaire un intervalle de valeurs de ppm (on peut se limiter aux motifs comprenant seulement les atomes CHON)

Variables : 
    -familles : liste des motifs candidats pour chaque famille

Sortie : la liste des motifs candidats pour chaque famille
 
Algo :
Pour tout groupe i d’hydrogènes    
Pour tout motif moléculaire de la table
              /* on vérifie que le motif peut correspondre au pic avec valeur ppm et nombre de H */
              Si tailleH[motif] appartient à nbH && valppm[i] est compris dans l’intervalle de valeurs du motif
                             ajout du motif dans familles[i]

**Algo 2** : générer toutes les molécules possibles en reliant les familles entre elles
C'est pour cette partie où c'est plus embêtant comme il y a énormément de possibilités, si on a sélectionné beaucoup de motifs.

**Comment by ColineUVSQ** [comment]
Je sais pas si ça peut être utile, mais on a aussi trouvé des tables pour les valeurs de ppm avec des vraies valeurs moyennes plutôt que des intervalles graphiques. Je les rajoute dans le projet.

**Comment by vxid** [comment]
Merci pour les tables. Normalement j'ai déjà mis les groupes les plus vonnus dans le fichier molecules.py

**Comment by vxid** [comment]
Pour l'algo que je fais, tout se trouve dans test.py (il y a pas mal de changements que j'ai pas encore push). L'idée serait ensuite de combiner toutes les combinaisons de groupes obtenus après élimination avec un solveur à la OPL.

**Comment by ColineUVSQ** [comment]
Ok
@edernlehyaric  Tu dis dans ton deuxième test que toutes les familles doivent être différentes, car sinon elles se retrouveraient sur le même pic, mais j'en suis pas sûre, parce que si elles n'ont pas le même environnement autour, ce sera pas le cas, même si elles sont identiques.

**Comment by vxid** [comment]
True. Exemple simple avec CH3-CH2-CH2-OH (vokr avec le solveur en ligne).
