### ISSUE TITLE
Organiser un chat

### ISSUE THREAD

**Issue by vxid** [vxid/rmn#6]
@ColineUVSQ @edernlehyaric @BintouFOFANA 

On s'organise un chat cet aprem ? J'ai l'impression qu'on bosse trop sur des choses en parallele là...

**Comment by ColineUVSQ** [comment]
Je sais que Bintou travaille jusqu'à 21h ce soir, donc elle, elle pourra pas

**Comment by edernlehyaric** [comment]
dispo quand vous voulez comme vous voulez (ts skype discord etc)

2017-11-29 16:27 GMT+01:00 ColineUVSQ <notifications@github.com>:

**Comment by ColineUVSQ** [comment]
OK

**Comment by edernlehyaric** [comment]
J'arriverai vers midi vingt. Train toutes demi heure à Massy

**Comment by ColineUVSQ** [comment]
OK, on se retrouvera à la salle de Germain du jeudi matin ?

**Comment by edernlehyaric** [comment]
Oh mon dieu 29min attente Massy. Balle dans la tête

**Comment by ColineUVSQ** [comment]
Tu arrives quand du coup?

**Comment by edernlehyaric** [comment]
Je suis là, quelle salle ?

**Comment by ColineUVSQ** [comment]
G204

**Comment by BintouFOFANA** [comment]
Bravo tu as survécu à ta balle

**Comment by BintouFOFANA** [comment]
j'ai trouvé ce petit doc sur la 2d , je le trouve pas mal après  j'ai pas tout lu
je vous donne le lien 
[http://eos.univ-reims.fr/LSD/JmnSoft/Teaching/vietnam2003.pdf]

**Comment by BintouFOFANA** [comment]
je sais que ça n'a rien avoir avec le projet mais il neige c'est tout blanc
trop contente

**Comment by ColineUVSQ** [comment]
:)

**Comment by edernlehyaric** [comment]
ça rigole 0 à orsay
https://imgur.com/a/CcwVM

2017-11-30 20:07 GMT+01:00 BintouFOFANA <notifications@github.com>:

**Comment by BintouFOFANA** [comment]
lol bcp plus à sannois
