### ISSUE TITLE
Rapport

### ISSUE THREAD

**Issue by ColineUVSQ** [vxid/rmn#7]
Est-ce que vous croyez qu'il faut être formel pour expliquer l'algorithme (avec des notations et tout), ou on peut juste expliquer avec des phrases ?

**Comment by edernlehyaric** [comment]
je vais faire un petit manuel pour mon truc sur la rmn 1H, genre 2-3 pages,
donc dans le rapport je pense qu'on peut rester formel

**Comment by vxid** [comment]
Je viens de finir ma partie de l'algo donnant les combinaisons d'atomes. Il me reste à tester si ça marche...

**Comment by ColineUVSQ** [comment]
Du coup, on prendra peut-être l'exemple du propanol pour mettre dans le rapport. Tu testes avec les RMN que nous a données le prof de chimie ou avec le logiciel en ligne qui les crée à partir de la molécule ?

**Comment by BintouFOFANA** [comment]
dsl, je n'avais pas internet

**Comment by BintouFOFANA** [comment]
Edern
personnellement si ton manuel permet d'expliquer ce que tu as fait sur la rmn 1H, je pense que c'est cela le but du rapport il faut donc l'ajouter au rapport

**Comment by vxid** [comment]
Je viens de em rendre compte que mon algo sort n'importe quoi, et notamment beaucoup trop d'atomes d'oxygène.

**Comment by vxid** [comment]
Sinon cadeau! N'hésitez pas si vous voyez des erreurs.

[game-theory.pdf](https://github.com/vxid/rmn/files/1534473/game-theory.pdf)

**Comment by BintouFOFANA** [comment]
Merci pour le doc.

**Comment by BintouFOFANA** [comment]
Pour l'algo ce n'est pas grave, on se concentrer  le rapport  parce qu'il ne nous reste plus beaucoup de temps et c'est pour bientôt les partiels

**Comment by ColineUVSQ** [comment]
@vxid  Et donc, ça marche pas, même pour un petit exemple ?

**Comment by edernlehyaric** [comment]
si je vais pondre un truc qui marche, je regarderai ça ce soir

2017-12-06 15:08 GMT+01:00 ColineUVSQ <notifications@github.com>:

**Comment by vxid** [comment]
Oui mais j'ai fait ça hier rapidement. Je regarde ce soir aussi. Ca ne devrait pas changer le contenu du rapport cela dit.

@edernlehyaric On peut en discuter ce soir sur Discord

**Comment by edernlehyaric** [comment]
je te fournis tout ça ce soir/nuit. va falloir que j'essaye à la main et
que j'ai de la chance !

**Comment by ColineUVSQ** [comment]
On y croit :)

**Comment by BintouFOFANA** [comment]
Je vous réponds par mail dsl je suis au boulot.
Coline, concernant le rapport tu préfère que je te le dise par mail ou que
je le mette en comparaître dans le code?

**Comment by ColineUVSQ** [comment]
Tu peux écrire directement dans le rapport. C'est bien ça, ta question ?

**Comment by ColineUVSQ** [comment]
Vous avez des documents de bibliographie à mettre dans le rapport ?

**Comment by BintouFOFANA** [comment]
SVP rappelez moi quel était le problème lié au dédoublement des pics dans les spectres rmn?

**Comment by ColineUVSQ** [comment]
Quand on a un dédoublement sur un pic, on ne peut plus dire que son nombre de voisins est le nombre de sous pics — 1

**Comment by BintouFOFANA** [comment]
merci ma puce

2017-12-07 14:06 GMT+01:00 ColineUVSQ <notifications@github.com>:

**Comment by BintouFOFANA** [comment]
edern pour ton algo tu utilises les données de Maxime en entrée?

**Comment by vxid** [comment]
Le problème c'est que mes données sont pas super propres. J'arrive à générer le produit cartésien des groupes possibles mais je bloque sur comment correctmenet compter le nombre d'atome de ces groupes...

**Comment by ColineUVSQ** [comment]
Ah. Tu regardes le nombre de groupes voisins de chaque groupe, et tu compares au nombre de liens sortants dans le motif, c'est ça ? Et du coup, si y'a le même nombre, c'est bon, tu ajoutes juste le nombre d'atomes du motif, et si y'en a plus dans la molécule, tu mets le motif plusieurs fois. C'est ça, ton algo ?

**Comment by ColineUVSQ** [comment]
En regardant ton code, je me dis que ce qui coince peut-être, c'est que si le nombre de liens sortants dans le motif est le même que le nombre de groupes voisins, tu prends comme amount le plus petit des deux. Mais genre, si y'en a 2 pour chaque, il faudrait prendre un seul motif, non ?

**Comment by vxid** [comment]
La partie du code en question:

```python
    for combnumber, combination in enumerate(possibilities):
        print("Combination #", combnumber+1)
        atoms = [0,0,0,0]
        for idx, group in enumerate(combination):
            a = len(group.links)
            b =  number_of_neighbouring_groups[idx]
            amount = 1
            if a >= b:
                amount = b
            else:
                i = 2
                while True:
                    if a*i < b:
                        i+=1
                    else:
                        amount = a*i
                        break
            for idx, atom in enumerate(group.atoms):
                atoms[idx] += amount * atom

```

**Comment by vxid** [comment]
Je liste les produits cartésiens (pas de problème jusqu'ici) et pour chacun d'entre eux je commence avec une liste d'atomes vide. Ensuite, pour chaque groupe de la combinaison en cours je calcule:

- Le nombre de groupes voisins pour UNE instance de ce groupe (e.g. un groupe alcool n'a qu'un seul voisin). Valeur stockée dans `a`.
- Le nombre de voisins du groupe dans la matrice d'adjacence, stocké dans `b`.

Après, mon idée (qui est probablement fausse, j'étais crevé en écrivant ça) est la suivante:
On itère sur les groupes de la combinaison. Chacun est au moins représenté une fois (sinon il n'apparaîtrait pas sur le spectre). Ensuite, si cette famille a naturellement plus de liens qu'elle n'a de voisins, c'est qu'elle est liée à plus d'une fois à ce voisin.
(et donc première erreur, c'est le nombre du voisin qui doit être égal à b, pas du groupe en question).
SI le nombre est inférieur, je double la quantité du groupe jusqu'à avoir une relation stable (pas sûr que ça soit suffisant d'ailleurs).

Je corrige ça et je réuploade.

**Comment by vxid** [comment]
Et bien sûr je viens de me rendre compte d'un autre problème:

Si un groupe a deux voisins différents, et que a > b, comment choisir lequel des voisins on double?

**Comment by ColineUVSQ** [comment]
Moi, je vois les choses comme ça : 
si a < b alors le motif doit être présent plusieurs fois (au moins 2)
si b < a alors c'est impossible parce que ça voudrait dire que le motif a moins de liens que le groupe donc c'est pas le bon motif
si a = b alors c'est bon le groupe = un exemplaire du motif

**Comment by vxid** [comment]
Je nettoye mon code et je te donne mes résultats. Mais déjà ma matrice de voisinage fait n'importe quoi donc....

**Comment by BintouFOFANA** [comment]
Si ta matrice de voisinage ne fonctionne pas très bien, on se contente juste d'expliquer ce que le code fait en mentionnant les limites dans le rapport et c'est bon

**Comment by vxid** [comment]
Non c'est bon c'est réglé, c'est juste que la diagonale est dans l'autre sens.

**Comment by vxid** [comment]
Je teste l'idée de Coline, c'est prêt dans 5 min.

**Comment by ColineUVSQ** [comment]
@BintouFOFANA  Ce serait mieux quand même de mettre dans le rapport un exemple qui a marché...

**Comment by BintouFOFANA** [comment]
ok

**Comment by vxid** [comment]
@ColineUVSQ 

Mais si on a `a > b`, ça ne veut pas plutôt dire qu'il faut plusieurs voisins tout simplement?

Par exemple. Si le groupe que je regarde a trois liens naturellement et qu'il a deux voisins différents, on peut très bien avoir 2 fois l'un (avec liaison de 1 pour ce groupe par exemple) et une fois l'autre (liaison de 2 par exemple), auquel cas la molécule est viable.

**Comment by vxid** [comment]
Et a contrario, si `a < b`, cela veut dire qu'il faut augmenter le nombre d'instances du groupe qu'on regarde actuellement. (Par exemple, le groupe que l'on regarde est un CH2, ayant deux liens et il a trois voisins différents, alors on sait qu'il y en a au moins deux)

**Comment by ColineUVSQ** [comment]
Oui, tu as raison... A tous les coups, il y a sûrement d'autres cas auxquels on n'a pas pensé... Par exemple, pour une famille à trois liens pour un groupe à 2 voisins, qu'en fait, dans l'un de ces voisins, il y ait en fait 2 exemplaires du groupe de même environnement. Je vois pourquoi tu parlais tout à l'heure de tas de cas compliqués ^^. Mais bon, tant pis, si déjà ça donne des résultats pas aberrants...

**Comment by vxid** [comment]
Je peux tenter un algo malin du genre commencer par augmenter le nombre de groupes avec le plus grand nombre de liens mais ça ne sera sûrement pas exhaustif...

**Comment by BintouFOFANA** [comment]
tu as raison dans le sens ou si a>b cela nous permettrait de prendre en compte les liaisons doubles.
Après c'est à nous de définir notre domaine de définition pour travailler

**Comment by BintouFOFANA** [comment]
Et tu as déjà une idée de l'algo?

**Comment by ColineUVSQ** [comment]
@BintouFOFANA Oui, on va être obligé de faire un truc restrictif... 
@vxid Peut-être, repars sur ce que tu disais quand tu corrigeais tes premières erreurs. Et à la question, quel voisin on double quand a > b, on peut peut-être le choisir aléatoirement ?

**Comment by vxid** [comment]
@ColineUVSQ @BintouFOFANA 
On peut, mais ça implique de potentiellement rater la bonne solution...
Je vais essayer de vois si en exhaustif c'est pas trop long à écrire.

**Comment by ColineUVSQ** [comment]
En testant tous les cas ?

**Comment by ColineUVSQ** [comment]
C'est vrai que comme les valences sont quand même limitées, c'est peut-être envisageable de tout tester...

**Comment by BintouFOFANA** [comment]
Ok essaie et on verra

**Comment by ColineUVSQ** [comment]
4 voisins, c'est un peu le max

**Comment by ColineUVSQ** [comment]
Enfin, c'est surtout pour le nombre de liens sortants des familles que c'est limité...

**Comment by BintouFOFANA** [comment]
Au pire des cas si ça ne marche pas, on peut être restrictif et dire qu'on a la solution bonne dans un pourcentage

**Comment by vxid** [comment]
Autre problème amarrant: vu que tu modifies les quantités des autres groupes dynamiquement il faut passer plusieurs fois pour s'assurer que tout est bon...

Je regarde ça.

**Comment by vxid** [comment]
C'est pas typiquement un problème OPL ça cela dit?

**Comment by ColineUVSQ** [comment]
De quoi ? Le fait de modifier les autres groupes ?

**Comment by ColineUVSQ** [comment]
Ou carrément tout le problème ?

**Comment by vxid** [comment]
Trouver des quantités de groupe a_1, a_2, ..., a_N qui vérifient une valence correcte.

**Comment by ColineUVSQ** [comment]
Ce serait chouette. Il faudrait, du coup, "juste" le mettre sous forme de programme linéaire

**Comment by vxid** [comment]
Ma solution:

On suppose qu'on a trois groupes. Chaque groupe dispose d'un nombre connu d'atomes. Alors, pour a_1, a_2 et a_3 le nombre de représentants de chacun de ces groupes on a une collection d'atomes du style;

H = 2*a_1 + 3 a_3
O = a_2
C = a_1 + a_2

Je peux essayer de rapidement générer les valeurs de a (pas trop grandes) qui donnent une valence nulle à la fin.

**Comment by ColineUVSQ** [comment]
Ok

**Comment by ColineUVSQ** [comment]
Mais, je me demandais : Ca ne simplifierait pas les choses si on utilisait le fait qu'on sait quel groupe est lié à quel groupe ? Ca diminue le nombre de possibilités. Du coup, on n'est pas obligé de faire un produit cartésien complet.

**Comment by vxid** [comment]
Oui probablement, mais c'est vraiment pas simple à écrire. C'est justement tout le problème du projet. C'est pour ça que j'abandonne l'algo "malin" et que je brutefocre le nombre de molecules, c'est juste plus simple à écrire.

**Comment by ColineUVSQ** [comment]
Oui, d'accord. Tu t'en sors ?

**Comment by vxid** [comment]
Je te tiens au courant. Là j'ai généré toutes les combinaisons de n-uplets allant de 1 à 7. Je dois calculer la valence dessus ensuite.

**Comment by vxid** [comment]
Ok je suis trop fort. Non seulement ça fonctionne mais j'obtiens une solution unique haha.

**Comment by edernlehyaric** [comment]
upload les resultats je veux voir ça

**Comment by vxid** [comment]
Sur une MRN avec deux groupes possibles etdes possibilités jusqu'à 8 j'ai une réponse unique. Pour des nombre de groupes allant jusqu'à 80 j'en ai 9 (et ça prend moins d'une seconde)

**Comment by edernlehyaric** [comment]
Au fait il est est où le rapport ? pas sur github si ?

**Comment by vxid** [comment]
Non débrouillez-vous.

**Comment by vxid** [comment]
Je rigole je push.

**Comment by ColineUVSQ** [comment]
Ya le lien sur le read me à la fin

**Comment by vxid** [comment]
TU peux essayer avec tes propres valeurs @edernlehyaric mais assure-toi que la matrice soit bonne et que les valeurs RMN soient reconnues par les groupements que j'ai définis en bas de utils.py

**Comment by vxid** [comment]
Et juge pas mon code stp c'est honteux.

**Comment by ColineUVSQ** [comment]
@edernlehyaric  Tu as fait finalement un petit manuel de 2-3 pages, comme tu avais dit ? Dans tous les cas, ce serait bien que tu regardes le rapport pour voir si ça va ce qu'on dit sur ta partie

**Comment by BintouFOFANA** [comment]
lol oui @vxid tu es trop fort

**Comment by BintouFOFANA** [comment]
@edernlehyaric comme coline l'a dit si tu pouvais lire la partie du rapport concernant ton algo ce serait top parce que tu es le seul à connaitre OPL

**Comment by BintouFOFANA** [comment]
@vxid du coup la complexité de l'algo est toujours exponentielle ou pas?

**Comment by ColineUVSQ** [comment]
@edernlehyaric Ce serait bien aussi que tu essayes de lancer ton programme OPL avec les 9 possibilités que trouve Maxime, pour donner le nombre de molécules que tu obtiens. :)

**Comment by ColineUVSQ** [comment]
@BintouFOFANA Tu as rajouté dans le rapport, le doc du prof de chimie en biblio, finalement ?

**Comment by BintouFOFANA** [comment]
non pas encore

**Comment by edernlehyaric** [comment]
@ColineUVSQ les 9 resultats de maxime c'est [3.293, 1.228, 0.920], [3,6,3], [6,6,4] ?

**Comment by vxid** [comment]
@BintouFOFANA oui completement exponentiel

**Comment by ColineUVSQ** [comment]
@edern : ce serait les 9 résultats de nombres d'atomes que donne son algo à partir des données que tu donnes

**Comment by vxid** [comment]
En enlevant les doublons il y en a que 3

**Comment by vxid** [comment]
Et je suis presque sûr que ce sont des multiples

**Comment by edernlehyaric** [comment]
je vois je vois, mais on a pas les mêmes bornes, les molécules que je generent ne satisfont pas les pics. Tu as pris quelle molécule pour le spectre ? que je vois si j'ai pas oublié de rajouter une famille, ou si j'ai été trop strict sur certaines valeurs.

**Comment by edernlehyaric** [comment]
Dimethoxymethane ?

**Comment by vxid** [comment]
Je sais plus d'où je les sors. Essaye avec des valeurs à toi pour voir sinon

**Comment by ColineUVSQ** [comment]
C'est le propanol je crois. Edern, il ne te suffit pas d'avoir les valeurs du nombre d'atomes pour faire marcher ton algo ?

**Comment by ColineUVSQ** [comment]
En tout cas ce serait cool que tu testes avec le propanol

**Comment by edernlehyaric** [comment]
c'pas propanol (8,1,0,3) contr (8,2,0,3) ici, je trouve deux molécules candidates si j'abaisse une borne inf de 1.5 à 1.0

**Comment by edernlehyaric** [comment]
mais là je me bas avec l'isomorphisme, je viens de m'apercevoir que ma fonction les supprimait pas tous et je ne comprend pas pourquoi

**Comment by BintouFOFANA** [comment]
@edernlehyaric tu peux donner un pourcentage de suppression?

**Comment by edernlehyaric** [comment]
bha je genere 1000 molécules; en l’occurrence 99.98% de supp, sinon sur les resultats d'hier c'était plutoit 99.95% de supp, je gardait quelques dizaines de candidats sur les grosses molécules (y'a des exemples sur le folder resultats_edern)

**Comment by BintouFOFANA** [comment]
Ok , mais tu as une idée de ce qui bloque dans 
ta fonction?

**Comment by ColineUVSQ** [comment]
Sinon c'est pas grave, on met pas d'estimation sur le rapport.

**Comment by edernlehyaric** [comment]
j'ai résolu l'isomorphisme, c'était dû à ce que python c'est de la merde

**Comment by edernlehyaric** [comment]
https://imgur.com/a/PcezV

**Comment by edernlehyaric** [comment]
ça c'est ma génération avec le nb d'atomes et les pics

**Comment by edernlehyaric** [comment]
qu'est ce que vous entendez par "pourcentage de suppression" ?

**Comment by ColineUVSQ** [comment]
Ok merci. Euh, je sais pas le pourcentage de suppression. Et en fait, donc si j'ai bien compris, avant l'étape de détection des isomorphismes, tu as beaucoup de molécules, et en fait c'est presque toutes des isomorphismes. Tu en génères "juste" 1000, et c'est suffisant pour trouver la bonne pour le propanol, mais pour des plus grosses tu dois en générer plus ?

**Comment by edernlehyaric** [comment]
pour autre_example.png j'en avais généré 10.000
j'ai pas les valeurs exactes, mais si je devais deviner, je dirai que si je recupere 50 molécules uniques sur 1000 générations aléatoires, je dois en avoir grosso modo 70 uniques sur 10.000 générations aléatoires....
En gros, pas besoin d'en généré des millions, on a statistiquement fait le tour rapidement (dépend de nb_atomes evidemment)

**Comment by ColineUVSQ** [comment]
Ok, et tu es obligé de choisir un nombre de générations (10 000) parce que sinon le programme ne s'arrête pas ?

**Comment by edernlehyaric** [comment]
plus la molécule à trouver est compliquée, plus la probabilité de générer une molécule candidate pour les pics est faible.
Tout simplement, pour une molécule simple comme le propanol, j'ai besoin de générer un faible nombre (probablement quelques centaines de matrices) pour être quasi sûr de retrouver le propanol.
Pour le "another_example.png" (30 molécules). je n'avais trouvé aucune molécule candidate au bout de 1000 générations. 
J'ai essayé 10.000 pour voir si ça marchait et ça m'a trouver quelque chose de cohérent pour les pics d'entrée.

**Comment by edernlehyaric** [comment]
si j'avais fait ça bien j'aurai envoyé au programme des paquets de matrices jusqu'à ce qu'il trouve, ou jusqu'à ce qu'il soit statiquement déterminé que le combo liste_atomes/liste pics n'était pas compatibles. 
Mais ça demande de faire un peu de maths et ça c'est non

**Comment by ColineUVSQ** [comment]
:) d'accord, ok, je comprends. Et tu vérifies la connexité sur les 1000 molécules aussi ?

**Comment by edernlehyaric** [comment]
ouai, premiere chose que je fais c'est que sur ces 1000 graphes je ne garde que ceux qui sont uniques et connexes, ça m'en garde 50 environs en général

**Comment by ColineUVSQ** [comment]
Et dans les 50, tu vérifies qu'il y a bien les famille, et c'est là que pour le propanol tu en trouves une, et pour l'autre exemple, une dizaine ?

**Comment by edernlehyaric** [comment]
exact !

**Comment by ColineUVSQ** [comment]
:) J'ai encore une autre question :p : pour ta molécule another-example, tu as choisi une liste d'atomes au pif ?

**Comment by edernlehyaric** [comment]
plus ou moins en fait, je voulais orienté le truc pour trouver un ch3-n-co, vérifier que mon algo marchait bien. mais en effet la molécule existe pas, j'ai juste mis un peu de tout genre chinois à volonté

**Comment by ColineUVSQ** [comment]
D'acc, merci, je vais la mettre dans le rapport je pense

**Comment by edernlehyaric** [comment]
je ferai mon petit manuel d'execution cette nuit, vous rendre le projet à quelle heuredemain ?

**Comment by ColineUVSQ** [comment]
Je sais pas trop... dans la journée :) Moi je préfèrerais le matin si on est prêt, mais sinon c'est pas grave. On lui envoie le lien du projet Github, c'est ça ? Faudra sûrement le nettoyer un peu avant...

**Comment by edernlehyaric** [comment]
yep, et j'ai vraiment fait le souillon sur le code à la fin, j'espère que c'est pas un expert python sinon il và se récup un ulcère

**Comment by ColineUVSQ** [comment]
x) Ce serait embêtant ! Mais je pense que le code, il ne va faire que le survoler. Et je crois pas que ce soit un expert Python ^^

**Comment by edernlehyaric** [comment]
dans mon manuel je mettrai tous les point important de l'algo de toute façon. et quand j'aurai fini ça je nettoierai le repo, faudra en faire un nouveau pour les exams je pense

**Comment by ColineUVSQ** [comment]
Je pense aussi

**Comment by ColineUVSQ** [comment]
Il faut le mettre dans le répertoire "report" le rapport ?

**Comment by vxid** [comment]
Pas obligé mais c'etait fait pour!

**Comment by ColineUVSQ** [comment]
Ah ok :). On va enlever les trucs en trop avant d'envoyer le lien au prof ?

**Comment by vxid** [comment]
Super le rapport! Tu pourrais éventuellement rajouter la source .tex dans le dossier.

Sinon pour le nettoyage je vais tout bouger dans /src et fermer les issues.

**Comment by BintouFOFANA** [comment]
oui je pense après il va juste survoler le code comme tu l'as dit

**Comment by ColineUVSQ** [comment]
Ok, je mets le .tex dans le répertoire report

**Comment by vxid** [comment]
Super.

**Comment by vxid** [comment]
@edern Je supprime toutes les images et annexes du repo avant le rendu. Si tu veux les retrouver ça sera le commit d7f48e5

**Comment by ColineUVSQ** [comment]
Tu as laissé le petit manuel qu'Edern a écrit sur sa partie ?

**Comment by vxid** [comment]
Oups. J'ai réup!

**Comment by vxid** [comment]
On est bon? Je peux close?

**Comment by edernlehyaric** [comment]
petit erratum dans la page 7 du rapport,
la troisieme famille n'est pas C-CH3 mais C3H-C, je sais que mes noms sont ambigus, C3H-C est la famille qui correspond a un C entouré de 3C et d'un H. j'aurai dû la nommer autrement

**Comment by ColineUVSQ** [comment]
Ok, je modifie. On ne met rien dans le readme ?

**Comment by vxid** [comment]
Non, si ce n'est l'ordre d'éxecution des programmes si le prof veut tester, mais là il faut demander à @edernlehyaric

**Comment by edernlehyaric** [comment]
il va avoir du mal à tester quoi que ce soit de mon côté, faut opl est privé, et j'ai pas envie d'expliquer comment setup python pour igraph

**Comment by vxid** [comment]
AH true. Bah mais quand meême rapidement les étapes au cas où mais du coup c'est bon.

**Comment by ColineUVSQ** [comment]
OK, comme vous voulez. Dans les sources, le dossier nommé "edern", ça fait un peu bizarre, non ? On ne pourrait pas lui trouver un autre nom ?

**Comment by ColineUVSQ** [comment]
Et donc, c'est bon, on peut envoyer le lien au prof ?

**Comment by vxid** [comment]
Ok pour moi!

**Comment by ColineUVSQ** [comment]
Mais ça m'embête un peu de ne rien mettre dans le read me...

**Comment by vxid** [comment]
Si tu y tiens vraiment on peut rajouter une mini-arborescence en disant où est le rapport le code etc mais je pense pas que ça soit super important...

**Comment by ColineUVSQ** [comment]
Tu as sûrement raison, mais ok pour faire ça. Je le fais du coup, si tu veux.

**Comment by vxid** [comment]
Merci!

**Comment by ColineUVSQ** [comment]
C'est bon, c'est envoyé ! On peut fermer l'issue, je pense.
