### ISSUE TITLE
Corrections de partiels

### ISSUE THREAD

**Issue by vxid** [vxid/rmn#8]
J'en profite pour créer une thread pour les partiels, histoire de partager nos corrections.

J'ai commencé avec le premier sujet de théorie des jeux.

## Exercice 1
Un seul équilibre en strat pure M,G.

Pour les stratégies mixtes:

- H,M est un support, donnant p=(1/5,4/5,0) et q=(2/3,1/3)
- H,L est un support, donnant p=(1/2,0,1/2) et q=(1/3,2/3)
- M,L n'est pas un support car on obtient q=(1/2,1/2) et une utilité supérieur pour le joueur 1 quand il joue haut. 

EDIT : Je trouve ça étrange que j'obtienne un équilibre H,L ne contenant pas le choix en stratégie pure. Je sais pas si c'est normal...

## Exercice 2
Faux. Je le referai

## Exercice 3
Les joueurs reliant s1 à d1 prennent tous les deux le chemin à 5 (meilleure réponse dans tous les cas). Le joueur reliant s2 à d2 prend la route du milieu (coût de 4).
Le jeu a un potentiel par définition (car jeu de congestion). Je ne sais pas si suffisant mais c'était une propriété du cours.

## Exercice 4

Pas fait en cours

## Exercice 5

Pas vu et coupé

**Comment by edernlehyaric** [comment]
je regarde l'exam du lundi vite fait, et je pige quedalle à ce qu'il entend
par"décompositions en événements monotones"(ex1) ou "décompositions des
evts"(ex2). Je sais que le cours a beaucoup changé par rapport à l'année
dernière mais quand meme !

**Comment by vxid** [comment]
@edernlehyaric Oui, c'est pas le même cours du tout.

**Comment by vxid** [comment]
@edernlehyaric @ColineUVSQ @BintouFOFANA 

Je vous taggue pour que voyez l'issue

**Comment by vxid** [comment]
# Sujet de Théorie des jeux #2

## Exercice 1

Un équilibre de Nash en stratégies pures: M,D

En stratégies mixtes:
- H,M n'est pas un support car on obtient q=(1/2,1/2) et u_L(1/2,1/2) = 9/2 > u_H = u_M = 4
- M,L n'est pas un support car on obtient q=(2/3,1/3) et u_M(2/3,1/3) = 16/3 > u_H = u_L = 5
- M,L est support (forcément car il y en forcément un et H,M,L n'est pas support (il suffit pour cela de montrer que les deux premiers calculs de support donnent des probas q différentes, et qu'on ne peut donc pas combiner ces supports)). On a alors q=(1/3,2/3) et p = (0,4/5,1/5)

## Exercice 2

L'exemple de matching penny fonctionne ici (avec que des 1 et -1). Ici maxmin = -1 et minmax = 1. On passe donc en stratégies mixtes.

La MR est immédiate:

Pour joueur 1 E(u) = -1 * p + (1-p) = 1 - 2p (identique j2)
Donc le p qui maximise E(u) est p=1/2

## Exercice 3

Je pense que le plus simple ici est de prendre une situation d'équilibre intuitive et de montrer que cet équilibre est stable.
En posant les deux l = 0.4 on obtient un équilibre:

Chemin 1 : 0.4 + l = 0.8
Chemin 2 : 0.4 + 0 + 0.4 = 0.8
Chemin 3: l + 0.4 = 0.8

Les proportions sont alors de 40,20 et 40% respectivement et personne n'a intérêt à dévier.
Je sais pas si c'est suffisant.

## Exercice 4

Pas fait en cours

## Exercice 5

Pas fait en cours

## Exercice 6

On déroule l'algo:

A -> X
B -> Z
C refusé par X
C -> Z, B rejeté
B -> Y

On obtient (A,X), (C,Z) et (B,Y).

Pour la question 2 j'ai pas envie d'énumérer à la main mais je me demande si un epropriété du cour peut pas y répondre directement.

## Exercice 7

Pas vu en cours.

**Comment by BintouFOFANA** [comment]
Dans l'exo 1, on peut calculer les fonctions de meilleures réponse pour
pour obtenir les stratégies mixtes?

**Comment by ColineUVSQ** [comment]
Je crois pas, non ? Parce qu'il y a 3 stratégies pour le joueur 1

**Comment by BintouFOFANA** [comment]
Oui c'est vrai

**Comment by vxid** [comment]
# Théorie des Jeux - Sujet #3

## Exercice 1

Le tableau est déjà fourni dans le sujet. Un seul EN, A/C (ou A/D). Le joueur 1 a toujours intérêt à choisir A car cette stratégie domine les autres.

Pour l'équilibre parfait en sous-jeu:

1 choisira forcément E, donnant 0 pour 2. 2 prévoit cela et jouera nécessairment C, 1 prévoit cela et jouera nécessairement A.

## Exercice 2

2 équilibres de Nash en stratégies pures : (H,D) et (M,G)

En stratégies mixtes:

- (H,M) est un EN, donne q=(2/3,1/3) et p=(1/5,4/5,0)
- (H,L) est un EN donne q=(1/3,2/3) et p=(1/3,0,2/3)
- (M,L) n'est pas un EN (donne q=(1,0) et u_L = 0)

Flemme pour les MR

A priori oui car jeu à somme nulle donc par définition on a un EN. Flemme de le chercher en revanche.

## Exercice 3

Pas sûr qu'on ai vu les jeux de potentiels comme ça...

**Comment by edernlehyaric** [comment]
pas dans les partiels mais vérifiez sur la formule d'erlang(blocking
probability) que vous ayez pas écrit des erreurs. Je sais pas si c'est moi
qui ai mal noté ou le prof mais c'est pas E^B(c-1,E) / c + E^(c-1,E), mais
E*B(c-1,E) / c + E*(c-1,E)

def b(c,e):
    if c == 0:
        return 1
    tmp = b(c-1,e)
    return ((e*tmp)/(c + (e*tmp))) # pas power mais *

for step in range(0,5):
    print(b(150 + 5*step,150))

'''
cours         output
---------------------------------
(0.062)     0.06240288566461264
(0.044)     0.04355046159539241
(0.025)     0.028246328545616473
(0.017)     0.0167631266965363
(0.009)     0.0089649155436223
'''
Bon... aprés ... c'est pas super utile de savoir ça car je pense pas qu'il
nous demandera des résultats sur une fonction récursive à la main.

**Comment by BintouFOFANA** [comment]
Coucou
on pourrait décider de faire le même sujet d'exam de graphe par exemple et de discuter des résultats.
qu'est ce que vous en pensez?

**Comment by vxid** [comment]
Oui bonne idee. Je dois regler le probleme de l'algo sur le projet avant mais on peut faire ca apres.

**Comment by ColineUVSQ** [comment]
A ce propos d'ailleurs, en fait, ca aurait été pratique si Edern, tu avais pu utiliser le résultat de Maxime en entrée de ton programme, puisque c'est ça la continuité non ?

**Comment by BintouFOFANA** [comment]
oui ce serait mieux cet aprem

**Comment by edernlehyaric** [comment]
j'avais envie de faire un peu de cours du lundi, alors j'ai fait les 2
derniers exos de l'exam, si jamais vous voyez des erreurs dites le moi ![image:
Images intégrées 2][image: Images intégrées 1]

2017-12-07 14:13 GMT+01:00 BintouFOFANA <notifications@github.com>:

**Comment by vxid** [comment]
Tu dois les up direct depuis GitHub pour avoir les images.

**Comment by ColineUVSQ** [comment]
En tout cas, si vous avez de la biblio à rajouter dans le rapport, surtout hésitez pas :)

**Comment by BintouFOFANA** [comment]
@ColineUVSQ  tu te rappelles de l'exo que le prof de simul avait donné sur le Bottleneck  et qu'il n'a pas corrigé?

**Comment by ColineUVSQ** [comment]
Oui, je me rappelle :)

**Comment by BintouFOFANA** [comment]
tu l'avait fait?

**Comment by ColineUVSQ** [comment]
Oui, j'avais trouvé :pour la config 1 : Xmax = 1.25 jobs/s, pour la config 2 : Xmax = 2.5 jobs/s et pour la config 3 : Xmax=2.5 jobs/s aussi. Je sais plus à quoi ça correspondait, mais j'avais trouvé ça :)

**Comment by BintouFOFANA** [comment]
oui j'avais trouvé les mêmes choses, je ne sais plus à quoi ça correspond lol

**Comment by ColineUVSQ** [comment]
:) Xmax je crois que c'est le débit maximal

**Comment by BintouFOFANA** [comment]
Mais le bottleneck c'était quoi au fait?

**Comment by ColineUVSQ** [comment]
c'est le composant mal dimensionné qui fait qu'on a ce débit. Si on modifie ce composant ça augmente le débit. Pour la config 1 c'était le A et les deux autres le C, je crois.

**Comment by BintouFOFANA** [comment]
oui c'est cela. J'ai les mêmes résultats

**Comment by ColineUVSQ** [comment]
Ok cool

**Comment by BintouFOFANA** [comment]
Pour la config 1, on remplace B par C du coup Vc=75ms?

**Comment by ColineUVSQ** [comment]
Moi j'ai Dc = 75 ms

**Comment by BintouFOFANA** [comment]
je voulais mettre Dc pardon, comme le graphe ne changera pas du coup on aura Vc=Vb=3

**Comment by ColineUVSQ** [comment]
Oui, j'ai trouvé ça aussi

**Comment by BintouFOFANA** [comment]
ok merci ma puce

**Comment by ColineUVSQ** [comment]
De rien :) Tu sais quand on va rendre le projet demain ?

**Comment by BintouFOFANA** [comment]
aucune idée

**Comment by BintouFOFANA** [comment]
On doit changer des choses dans le rapport?

**Comment by BintouFOFANA** [comment]
On doit changer des choses dans le rapport?

**Comment by ColineUVSQ** [comment]
Edern me demandait ça. Je lui ai dit que je ne savais pas non plus. De toute façon, il ne reste plus qu'à mettre le rapport sur GitHub et arranger le readme ou des trucs comme ça.

**Comment by ColineUVSQ** [comment]
Non, je pense pas. Là, je finis juste de rajouter le deuxième exemple d'Edern et c'est bon.

**Comment by BintouFOFANA** [comment]
Oui, franchement je l'ai relu et je pense que c'est bon.
Aussi j'ai mis dans la conclusion que les isomorphismes sont supprimés à 99%

**Comment by ColineUVSQ** [comment]
OK cool

**Comment by BintouFOFANA** [comment]
On pourrait mettre un lien vers une doc mentation en OPL dans les références ou si @edernlehyaric  en a déjà ce serait cool

**Comment by ColineUVSQ** [comment]
Oui, c'est vrai. Faudrait le mettre dans les références.

**Comment by BintouFOFANA** [comment]
ok

**Comment by edernlehyaric** [comment]
A quoi correspondait le Nmax dans cet exercice (bottleneck)?

2017-12-08 1:07 GMT+01:00 BintouFOFANA <notifications@github.com>:

**Comment by ColineUVSQ** [comment]
C'est le nombre d'utilisateurs maximal que tu peux avoir, je crois

**Comment by edernlehyaric** [comment]
ok, je me demandais pourquoi Nmax était plus élevé dans la conf 2 que la conf 3, alors que la conf 3 a des temps de traitement plus courts

**Comment by ColineUVSQ** [comment]
Ouais, je ne sais pas trop non plus.... C'est le D qui change entre les deux, donc le temps de service, mais comme ya le même débit max...

**Comment by BintouFOFANA** [comment]
@ColineUVSQ  le système est meilleur dans la config 2

**Comment by ColineUVSQ** [comment]
Même si le temps de service est plus long (0.9s) ?

**Comment by BintouFOFANA** [comment]
Moi je trouve 0.9 pour la config 2 et 1.875 pour la config 3

**Comment by ColineUVSQ** [comment]
Ah, moi je trouve 0.75 pour la 3...

**Comment by edernlehyaric** [comment]
temps de service = somme vi*si ? si oui conf 3 c'est 0.75

**Comment by ColineUVSQ** [comment]
Tu as Da = 150 ms, Dcpu=200 ms et Dc = 400 ms ?

**Comment by ColineUVSQ** [comment]
Oui c'est ça la formule

**Comment by BintouFOFANA** [comment]
en config 2 ou 3?

**Comment by ColineUVSQ** [comment]
en 3

**Comment by BintouFOFANA** [comment]
Moi j'ai Da=300

**Comment by edernlehyaric** [comment]
cf1 : 1075
cf2 : 900
cf3 : 750

**Comment by BintouFOFANA** [comment]
en config 2

**Comment by BintouFOFANA** [comment]
pourquoi en 3 tu as 750?

**Comment by edernlehyaric** [comment]
16*25 + 3*100 +20*10 = 400 + 300 + 200

**Comment by edernlehyaric** [comment]
je cite coline "Tu as Da = 150 ms, Dcpu=200 ms et Dc = 400 ms "

**Comment by ColineUVSQ** [comment]
oui pour la config 3

**Comment by ColineUVSQ** [comment]
Du coup, c'est ton Da qui est différent, si tu as Da=300 en config 3

**Comment by BintouFOFANA** [comment]
cf3 on remplace A par B
Db devient 
Db=16*100

**Comment by edernlehyaric** [comment]
A par C, B par A

**Comment by edernlehyaric** [comment]
j'ai noté ça pour la cfg 3 perso

**Comment by ColineUVSQ** [comment]
Oué

**Comment by ColineUVSQ** [comment]
J'ai noté comme Edern

**Comment by ColineUVSQ** [comment]
C'est ça le souci alors

**Comment by ColineUVSQ** [comment]
On n'a pas noté la même chose :)

**Comment by BintouFOFANA** [comment]
moi A par B et B par C

**Comment by BintouFOFANA** [comment]
Je comprends  mieux pourquoi nos résultats sont différents

**Comment by BintouFOFANA** [comment]
Si vous avez noté la même chose c'est sans doute moi qui est mal noté

**Comment by BintouFOFANA** [comment]
Oui c'est le plus important

**Comment by edernlehyaric** [comment]
mais y'a un truc dans la logique des resultats que j'ai pas compris. Idéalement tu voudrais que Nmax soit le plus grand possible non ?

**Comment by ColineUVSQ** [comment]
Oui, c'est ça que je ne comprends pas non plus, pourquoi dans la meilleure des config (normalement la 3) le nombre max d'utilisateurs est plus petit...

**Comment by BintouFOFANA** [comment]
moi j'ai pas ce problème

**Comment by edernlehyaric** [comment]
la chance

**Comment by BintouFOFANA** [comment]
parce que  ma meilleure config est la 2

**Comment by ColineUVSQ** [comment]
lol, oui, mais toi t'as pas le bon énoncé :)

**Comment by BintouFOFANA** [comment]
lol ou c'est vous qui n'aviez pas le bon lol

**Comment by ColineUVSQ** [comment]
La probabilité est plus faible :p

**Comment by BintouFOFANA** [comment]
attendons de voir ce que maxime a noté lol

**Comment by ColineUVSQ** [comment]
:) Vous êtes ok pour que je mette le pdf du rapport sur github ?

**Comment by BintouFOFANA** [comment]
attendez je fais avec vos notes et on fera

**Comment by BintouFOFANA** [comment]
moi ça me va

**Comment by edernlehyaric** [comment]
quelque soit ce qu'on a noté je trouve pas les resultats cohérents entre Nmax et le temps de service pour le disque

**Comment by edernlehyaric** [comment]
genre on améliore juste un disque, et ça baisse Nmax ... pô compris

**Comment by ColineUVSQ** [comment]
Oué, je sais pas.... 
Je vais aller dormir, je vous dis bonne nuit :)

**Comment by edernlehyaric** [comment]
bonne nuit

**Comment by BintouFOFANA** [comment]
moi aussi

**Comment by BintouFOFANA** [comment]
bonne nuit à vous

**Comment by edernlehyaric** [comment]
tchuuss

**Comment by vxid** [comment]
Je propose de changer de repo pour les partiels. On peut faire un sujet au format .md et se corriger comme ça.

**Comment by ColineUVSQ** [comment]
Oui, c'est ce qu'on se disait aussi

**Comment by BintouFOFANA** [comment]
On pourrait aussi faire un repo par matière

**Comment by vxid** [comment]
Non trop galère je pense. Un dossier par matière suffira je pense

**Comment by BintouFOFANA** [comment]
ok ça me va

**Comment by BintouFOFANA** [comment]
@ColineUVSQ, en simul le 2ième exemple sur les proba de retour tu pourrais me donner tes résultats stp?

**Comment by edernlehyaric** [comment]
tu parles de quel problempe ?

**Comment by BintouFOFANA** [comment]
je parle du calcul de s proba de retour, les Fi

**Comment by BintouFOFANA** [comment]
c'est un exemple du cours. Quand on a parlé de l'irréductibilité des chaines et de la périodicité on avait fait des exemples pour calculer les proba de retour en i( i état )

**Comment by edernlehyaric** [comment]
je vois, et l'exemple dont tu parles c'est 
0.5  0.5  0
0     0     1
0     1     0

ou 
1/3  2/3    0    0
0      0    1/2 1/2
0      0      0     1
0      1      0     0 
?

**Comment by BintouFOFANA** [comment]
oui la seconde matrice

**Comment by BintouFOFANA** [comment]
c'était quoi les proba

**Comment by vxid** [comment]
On peut ouvrir un autre repo ou utiliser discord plutôt ? C'est pas super adapté les issues lol.

**Comment by edernlehyaric** [comment]
ok, tu veux bien le créer ? j'ai jamais fait !

**Comment by vxid** [comment]
Done.

**Comment by edernlehyaric** [comment]
sinon vite les res bintou : 
f(i,n) -> f(0,1) = 1/3, f(0,n) : n > 1 = 0 (car 0 est transitoire)
f(3,1) = 0, f(3,2) = 1/2, f(3,3) = 1/2, f(3,n) : n > 3 = 0
f3 = somme f(3,n) = 1, donc f3 réccurent positif

**Comment by BintouFOFANA** [comment]
ok merci
